version: '3'
services:
  postgis:
    image: postgis/postgis:16-3.4-alpine@sha256:1e7bf393a6589c3d6f10c09cae506d3fedfa3d035ad37c5715c8bbf3a961b185
    container_name: ivao_tracker_postgis
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ivao
      POSTGRES_PASSWORD: ivao
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:Z"
    healthcheck:
      test: pg_isready -U ivao -h localhost -t 5 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s

  ivao_tracker:
    container_name: ivao_tracker
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
