services:
  postgis:
    image: postgis/postgis:17-3.4-alpine@sha256:5a1dbedac34e0e6663f8b7190d393339571f1cb3ecb2ab2f724524b4f3c7956e
    restart: always
    container_name: ivao_tracker_postgis
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: ivao
      POSTGRES_PASSWORD: ivao
      POSTGRES_DB: ivao
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - "pgdata:/var/lib/postgresql/data:Z"
    healthcheck:
      test: pg_isready -U ivao -h localhost -t 5 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s

  ivao_tracker:
    restart: always
    container_name: ivao_tracker
    depends_on:
      - postgis
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    volumes:
      - "./conf/config.toml:/ivao_tracker/config.toml:Z"

volumes:
  pgdata:
    driver: local
