version: '3'
services:
  postgis:
    image: postgis/postgis:16-3.4-alpine@sha256:681931a625df344215e9b8998bf34daf146b6a395ceacee4439eb9c85869239f
    restart: always
    container_name: ivao_tracker_postgis
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ivao
      POSTGRES_PASSWORD: ivao
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:Z"
      - "./conf/postgresql.conf:/etc/postgresql.conf"
      - "./conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf"
    healthcheck:
      test: pg_isready -U ivao -h localhost -t 5 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s

  ivao_tracker:
    container_name: ivao_tracker
    depends_on:
      - postgis
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
