version: '3'
services:
  postgis:
    image: postgis/postgis:16-3.4-alpine@sha256:5ed6475595caee4d216c399098d4d8def6c0234298e7491a287539201ca63a4c
    container_name: ivao_tracker_postgis
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ivao
      POSTGRES_PASSWORD: ivao
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:Z"
    healthcheck:
      test: pg_isready -U ivao -h localhost -t 5 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s

  ivao_tracker:
    container_name: ivao_tracker
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
