[airports]
url = "https://ourairports.com/airports.csv"
interval = 43200

[ivao]
whazzup_url = "https://api.ivao.aero/v2/tracker/whazzup"
interval = 20

[db]
username = "ivao"
password = "ivao"
host = "postgis"
port = 5432
database = "ivao"
