name: CI

on:
  push:
    paths:
      - '**.py'
      - 'Makefile'
      - 'pyproject.toml'
      - '.github/workflows/main.yml'
    branches: [ main ]
  pull_request:
    paths:
      - '**.py'
      - 'Makefile'
      - 'pyproject.toml'
      - 'docker/docker-compose.yml'
      - 'docker/Dockerfile'
      - '.github/workflows/main.yml'
    branches: [ main ]

  workflow_dispatch: # allows running manually

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12,3.13]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=\"$HOME/.local/bin:\$PATH\"" >> $GITHUB_ENV
      - name: Lock dependencies
        run: poetry lock
      - name: Install project
        run: make install
      - name: Run tests
        run: |
          source $(poetry env info --path)/bin/activate
          make test
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
